In [3]:
import numpy as np
import matplotlib.pylab as plt
import scipy.stats as st
import seaborn as sns
import pandas as pd

In [4]:
import statsmodels.api as sm

# Образование и вера

General Social Survey — ежегодный опрос населения США, записывается около 5000 факторов. Из опроса 2008 года выбраны данные о вере и образовании 2000 опрошенных. Есть ли связь между степенью веры и уровнем образования?

**2008 General Social Survey, National Opinion Research center (Agresti A. Categorical Data Analysis. — Hoboken: John Wiley & Sons, 2013, табл. 3.2)**

In [5]:
data= pd.read_csv('./fe.txt', delimiter='\t')

In [6]:
data.head()

Highest degree  don’t believe  no way to find out  \
0          Less than high school              9                   8   
1  High school or junior college             23                  39   
2           Bachelor or graduate             28                  48   

   some higher power  believe sometimes  believe but doubts  know God exists  
0                 27                  8                  47              236  
1                 88                 49                 179              706  
2                 89                 19                 104              293

## Pearson $\chi^2$

In [7]:
values = data.values[:, 1:].astype(np.float)

In [8]:
values

array([[  9.,   8.,  27.,   8.,  47., 236.],
       [ 23.,  39.,  88.,  49., 179., 706.],
       [ 28.,  48.,  89.,  19., 104., 293.]])

In [9]:
st.chi2_contingency(values)

(76.1483261658133,
 2.842572791195739e-12,
 10,
 array([[ 10.05  ,  15.9125,  34.17  ,  12.73  ,  55.275 , 206.8625],
        [ 32.52  ,  51.49  , 110.568 ,  41.192 , 178.86  , 669.37  ],
        [ 17.43  ,  27.5975,  59.262 ,  22.078 ,  95.865 , 358.7675]]))

## G-test

In [10]:
st.chi2_contingency(values, lambda_ = "log-likelihood")

(73.18790888970611,
 1.0705703476205307e-11,
 10,
 array([[ 10.05  ,  15.9125,  34.17  ,  12.73  ,  55.275 , 206.8625],
        [ 32.52  ,  51.49  , 110.568 ,  41.192 , 178.86  , 669.37  ],
        [ 17.43  ,  27.5975,  59.262 ,  22.078 ,  95.865 , 358.7675]]))

## Коэффициент V Крамера

In [11]:
def cramers_corrected_stat(confusion_matrix):
    """ calculate Cramers V statistic for categorial-categorial association.
        uses correction from Bergsma and Wicher, 
        Journal of the Korean Statistical Society 42 (2013): 323-328
    """
    chi2 = st.chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum()
    r, k = confusion_matrix.shape
    return ### Ваш код

In [12]:
stat = cramers_corrected_stat(values)
stat

## Корреляция между порядковыми переенными

In [13]:
n = 0
pc = 0
pd = 0
pt = 0
for i in range(3):
    for j in range(6):
        for k in range(3):
            for z in range(6):
                current = values[i, j]*values[k, z]
                n+=current
                if i==k or j == z:
                    ### Ваш код
                elif i>k and j>z:
                    ### Ваш код
                else:
                    ### Ваш код
gamma = ### Ваш код
print(gamma)


IndentationError: expected an indented block (<ipython-input-13-8da46ab1c848>, line 13)

## Встречаемость через длину

In [14]:
new_data = []
for i in range(values.shape[0]):
    for j in range(values.shape[1]):
        new_data.extend([[i,j]]*int(values[i,j]))
new_data = np.array(new_data)
new_data.shape

(2000, 2)

In [15]:
st.pearsonr(new_data[:,0], new_data[:, 1])[0]

-0.16203759162368087

In [16]:
st.kendalltau(new_data[:,0], new_data[:,1])[0]

-0.1475371344671059

In [17]:
st.spearmanr(new_data[:,0], new_data[:,1])[0]

-0.16436204271249027

In [18]:
data.values

array([['Less than high school', 9, 8, 27, 8, 47, 236],
       ['High school or junior college', 23, 39, 88, 49, 179, 706],
       ['Bachelor or graduate', 28, 48, 89, 19, 104, 293]], dtype=object)

## Через statmodels

In [ ]:
table = sm.stats.Table(data.values[:, 1:])

In [ ]:
table.table_orig

In [ ]:
chi2_test = table.test_nominal_association()

In [ ]:
chi2_test.statistic

In [ ]:
chi2_test.pvalue

## Корреляция Мэтьюся
$$MCC = \frac{ad-bc}{\sqrt{(a+b)(a+c)(b+d)(c+d)}}$$

In [ ]:
for i in range(1, 3):
    print('#'*30)
    print (data.values[i, 0])
    for j in range(1, 6):
        a = values[i:, j:].sum()
        b = values[i:, :j].sum()
        c = values[:i, j:].sum()
        d = values[:i, :j].sum()
        C = ### Ваш код
        
        print('{}: {}'.format(data.columns[j+1], C))
