In [16]:
from sklearn import datasets
import numpy as np
X, Y = datasets.load_iris(return_X_y=True)

In [17]:
# выделение 3 классов отдельно
type1, type2, type3 = X[0:50], X[50:100], X[100:150]

In [23]:
# определение среднего значения для каждого признака
type1_m = np.mean(type1, axis = 0)
type2_m = np.mean(type2, axis = 0)
type3_m = np.mean(type3, axis = 0)

In [24]:
# разница между средними для каждого признака между определенными классами
difference_1vs2 = type1_m-type2_m
difference_2vs3 = type2_m-type3_m
difference_1vs3 = type1_m-type3_m

In [28]:
# std для каждого признака и для каждого из классов
type1_std = np.std(type1, axis = 0)
type2_std = np.std(type2, axis = 0)
type3_std = np.std(type3, axis = 0)

In [33]:
# according to Cohen's, define pooled standard deviation
std_1plus2 = np.sqrt((49/98)*(type1_std**2 + type2_std**2))
std_1plus3 = np.sqrt((49/98)*(type1_std**2 + type3_std**2))
std_2plus3 = np.sqrt((49/98)*(type2_std**2 + type3_std**2))

In [34]:
# according to Cohen's, count effect size
effect_size_1vs2 = difference_1vs2/std_1plus2
effect_size_1vs3 = difference_1vs3/std_1plus3
effect_size_2vs3 = difference_2vs3/std_2plus3

In [43]:
print(effect_size_1vs2)
print(effect_size_1vs3)
print(effect_size_2vs3)

[-2.12556021  1.91019358 -7.9787342  -6.88526875]
[ -3.10848097   1.30316731 -10.09873465  -8.64403645]
[-1.13726312 -0.64766148 -2.54634797 -2.95477035]
